AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

  Lambda that disables any AWS Access key not used in the past 90 days

Globals:
  Function:
    Runtime: python3.8
    Timeout: 300
    MemorySize: 256

Resources:
  LambdaFunction: 
    Type: AWS::Serverless::Function
    Properties:
      Description: 'lambda for deleting unused keys'
      Role: arn:aws:iam::012345678912:role/delete-unused-keys-lambda-role
      FunctionName: DeleteUnusedKeysLambda
      CodeUri: src
      Handler: DeleteUnusedKeys.lambda_handler
      Tracing: Active

  EBTrigger: 
    DependsOn: LambdaFunction
    Type: AWS::Events::Rule
    Properties:
      Description: >
        EventBridge Trigger for deleting unused keys Lambda
      Name: DeleteKeysCheck1d
      ScheduleExpression: rate(1 day)
      Targets: 
        - Arn: "arn:aws:lambda:us-west-2:012345678912:function:DeleteUnusedKeysLambda"
          Id: 'DeleteUnusedKeysLambda'
      State: 'ENABLED'

  AllowEBInvoke: 
    DependsOn: EBTrigger
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 'DeleteUnusedKeysLambda'
      Action: 'lambda:InvokeFunction'
      Principal: 'events.amazonaws.com'
      SourceArn: "arn:aws:lambda:us-west-2:012345678912:function:DeleteUnusedKeysLambda"
